name: vrts

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --immutable

      - name: Building
        run: yarn build

      - name: Running Visual Regression Tests
        run: yarn vrt
        timeout-minutes: 20
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
